apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-player
  labels:
    app: video-player
spec:
  replicas: 2
  selector:
    matchLabels:
      app: video-player
  template:
    metadata:
      labels:
        app: video-player
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: video-player
        image: bskkmg/video-player:v1.0.0
        imagePullPolicy: "Always"
        ports:
        - containerPort: 3000
